SELECT 'CREATE DATABASE customer_service'
WHERE NOT EXISTS (
    SELECT 1 FROM pg_database WHERE datname = 'customer_service'
)\gexec

SELECT 'CREATE DATABASE account_service'
WHERE NOT EXISTS (
    SELECT 1 FROM pg_database WHERE datname = 'account_service'
)\gexec

\connect customer_service;

CREATE TABLE IF NOT EXISTS persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    age INTEGER NOT NULL,
    identification VARCHAR(50) NOT NULL UNIQUE,
    address VARCHAR(180) NOT NULL,
    phone VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS customers (
    person_id BIGINT PRIMARY KEY,
    customer_id VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL,
    status BOOLEAN NOT NULL,
    CONSTRAINT fk_customers_person
        FOREIGN KEY (person_id)
        REFERENCES persons (id)
        ON DELETE CASCADE
);

INSERT INTO persons (id, name, gender, age, identification, address, phone) VALUES
    (1, 'Jose Lema', 'Masculino', 30, '0102030405', 'Otavalo sn y principal', '098254785'),
    (2, 'Marianela Montalvo', 'Femenino', 28, '1112131415', 'Amazonas y NNUU', '097548965'),
    (3, 'Juan Osorio', 'Masculino', 35, '2122232425', '13 junio y Equinoccial', '098874587')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    gender = EXCLUDED.gender,
    age = EXCLUDED.age,
    identification = EXCLUDED.identification,
    address = EXCLUDED.address,
    phone = EXCLUDED.phone;

INSERT INTO customers (person_id, customer_id, password, status) VALUES
    (1, 'JL001', '1234', TRUE),
    (2, 'MM001', '5678', TRUE),
    (3, 'JO001', '1245', TRUE)
ON CONFLICT (person_id) DO UPDATE SET
    customer_id = EXCLUDED.customer_id,
    password = EXCLUDED.password,
    status = EXCLUDED.status;

SELECT setval('persons_id_seq', GREATEST((SELECT COALESCE(MAX(id), 1) FROM persons), 1), true);

\connect account_service;

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(50) NOT NULL UNIQUE,
    account_type VARCHAR(40) NOT NULL,
    initial_balance NUMERIC(19, 2) NOT NULL,
    available_balance NUMERIC(19, 2) NOT NULL,
    customer_id VARCHAR(50) NOT NULL,
    customer_name VARCHAR(120) NOT NULL,
    status BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_date TIMESTAMP NOT NULL,
    movement_type VARCHAR(40) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    balance NUMERIC(19, 2) NOT NULL,
    account_id BIGINT NOT NULL,
    CONSTRAINT fk_movements_account
        FOREIGN KEY (account_id)
        REFERENCES accounts (id)
        ON DELETE CASCADE
);

INSERT INTO accounts (
    id,
    account_number,
    account_type,
    initial_balance,
    available_balance,
    customer_id,
    customer_name,
    status
) VALUES
    (1, '478758', 'Ahorro', 2000.00, 1425.00, 'JL001', 'Jose Lema', TRUE),
    (2, '225487', 'Corriente', 100.00, 700.00, 'MM001', 'Marianela Montalvo', TRUE),
    (3, '495878', 'Ahorros', 0.00, 150.00, 'JO001', 'Juan Osorio', TRUE),
    (4, '496825', 'Ahorros', 540.00, 0.00, 'MM001', 'Marianela Montalvo', TRUE),
    (5, '585545', 'Corriente', 1000.00, 1000.00, 'JL001', 'Jose Lema', TRUE)
ON CONFLICT (id) DO UPDATE SET
    account_number = EXCLUDED.account_number,
    account_type = EXCLUDED.account_type,
    initial_balance = EXCLUDED.initial_balance,
    available_balance = EXCLUDED.available_balance,
    customer_id = EXCLUDED.customer_id,
    customer_name = EXCLUDED.customer_name,
    status = EXCLUDED.status;

INSERT INTO movements (
    id,
    movement_date,
    movement_type,
    amount,
    balance,
    account_id
) VALUES
    (1, '2022-02-10 10:00:00', 'RETIRO', -575.00, 1425.00, 1),
    (2, '2022-02-10 11:00:00', 'DEPOSITO', 600.00, 700.00, 2),
    (3, '2022-02-10 12:00:00', 'DEPOSITO', 150.00, 150.00, 3),
    (4, '2022-02-08 09:00:00', 'RETIRO', -540.00, 0.00, 4)
ON CONFLICT (id) DO UPDATE SET
    movement_date = EXCLUDED.movement_date,
    movement_type = EXCLUDED.movement_type,
    amount = EXCLUDED.amount,
    balance = EXCLUDED.balance,
    account_id = EXCLUDED.account_id;

SELECT setval('accounts_id_seq', GREATEST((SELECT COALESCE(MAX(id), 1) FROM accounts), 1), true);
SELECT setval('movements_id_seq', GREATEST((SELECT COALESCE(MAX(id), 1) FROM movements), 1), true);
